feat: Add toast & fix calendar
yurixander/erc20-vault pull request #4
Opened 2024-11-09 16:42 UTC by mariopzt

- Agregar un toast para mostrar error de deposito.
- Arreglar el CSS del calendario.

2024-11-10 13:24 UTC, mariopzt commented
Voy a marcar esta como completado para que la revises y se mezcle porque esta un tin muy complicado aver si tu la puedes hacer y yo voy a hacer otra cosa @criss8x

2024-11-10 13:35 UTC, criss8X requested changes

2024-11-10 13:35 UTC, criss8X commented on src/components/Button.tsx
> +export const BUTTON_VARIANTS = cva(
`cva` devuelve una funcion, el nombre de la variable entonces deberia ser algo como `buttonVariants`

2024-11-10 13:35 UTC, criss8X commented on src/components/Toast.tsx
> +const TOAST_VARIANTS = cva(
igual aca el toastVariants anterior estaba bien ya que cva devuelve una funcion

2024-11-10 13:35 UTC, criss8X commented on src/containers/DepositButton.tsx
> +            description: error.message,
Si el error es lanzado por uno mismo en la funcion onError entonces estaria bien, pero rectificar que el error no sea lanzado automaticamente por una API ya que descubre informacion sobre la localizacion de archivos ect..., si el error es lanzado por uno mismo marcar esto como completado

2024-11-10 14:24 UTC, yurixander commented
@criss8X Toma este PR aver si lo puedes hacer tu

2024-11-10 14:56 UTC, criss8X commented
> @criss8X Toma este PR aver si lo puedes hacer tu

Si en breves reviso

2024-11-13 16:48 UTC, criss8X commented
> * Se arreglo el componente Calendar
> * Se resolvieron problemas de focus de el input y el boton de cerrar del modal
> * Se mejoro la accesibilidad de el componente input

![image](https://github.com/user-attachments/assets/3b629409-b50f-4222-942a-91010e4e0439)

2024-11-13 17:34 UTC, yurixander approved these changes

2024-11-13 18:45 UTC, lazaroysr96 commented on src/components/DepositList.tsx
> +          className="min-w-[100px]"
Aunque no existe en Tailwind algo como min-w-25, creo que se podría tratar de hacer los componentes siempre con valores de Tailwind.

2024-11-13 18:48 UTC, yurixander commented on src/components/DepositList.tsx
> +          className="min-w-[100px]"
@lazaroysr96 Este es uno de los casos en los cuales usar px específicos, eso de min w y h, ect.

2024-11-14 13:03 UTC, JohanDavid777 approved these changes

2024-11-14 14:01 UTC, lazaroysr96 commented on src/components/Toast.tsx
> +export const ToastProvider2: React.FC<{ children: React.ReactNode }> = ({
Aquí veo que se usa React.FC, React.ReactNode ...etc, aunque estos componentes provengan de una determinada librería, podríamos adaptarlos al estilo de programación que hemos  estado utilizando hasta el momento.

2024-11-14 14:07 UTC, lazaroysr96 approved these changes

2024-11-16 23:15 UTC, merged