feat: General code optimization
yurixander/erc20-vault pull request #8
Opened 2024-11-24 19:07 UTC by lazaroysr96

### Realizando Optimización General.

En este PR estaré revisando el código y resolviendo detalles respecto a componentes que se deban mejorar.

**Cambios realizados**

- Se solucionó problema con el calendario, anteriormente los días de la semana no se mostraban adecuadamente.

2024-11-26 13:30 UTC, criss8X requested changes
En lugar de parsear un booleano, y convertirlo a string, puedes usar un string fijo asi evitas parseos innecesarios, puedes poner como dato a guardar, `dark` si es modo oscuro, o `light` como modo claro y en caso de no estar ninguno pos el por defecto, tambien usaras constantes.

```ts
const DARK_MODE = "dark";
const LIGHT_MODE = "light"
```

2024-11-26 13:30 UTC, criss8X commented on src/hooks/useTheme.ts
> +  const isDarkMode = savedTheme ? JSON.parse(savedTheme) : false
esto debe ir dentro de un useEffect, no puede ir fuera

2024-11-26 13:30 UTC, criss8X commented on src/hooks/useTheme.ts
> +  const [isDarkTheme, setIsDarkTheme] = useState(isDarkMode)
al poner lo de arriba en un useEffect, quitas el isDarkMode y pones un valor por defecto como true

2024-11-26 13:30 UTC, criss8X commented on src/hooks/useTheme.ts
> +    localStorage.setItem("darkMode", JSON.stringify(isDarkTheme))
ahi en setItem, la `key` es mejor que el valor lo guardes en una constante fuera del hook en lugar de ponerlo literal, seria algo como:

```ts
const THEME_KEY = "theme_mode";

localStorage.setItem(THEME_KEY,  ....)
```

2024-12-08 16:46 UTC, Ariel11R approved these changes

2024-12-12 13:01 UTC, criss8X requested changes
![image](https://github.com/user-attachments/assets/d706df18-51d5-4af0-931f-1d7d04600b73)

El calendario tiene bug los botones

2024-12-16 14:00 UTC, criss8X commented on src/components/ButtonSwitchTheme.tsx
> +"use client";
Te falto aqui quitar este "use client"

2024-12-16 14:02 UTC, criss8X commented on src/components/ButtonSwitchTheme.tsx
> +    <Button onClick={toggleTheme} className="size-8">
El button de shadcn tiene variantes, hay una que es la variante ghost normalmente usada para los `IconButton`, ademas tiene un argumento llamado `size` que te permite determinar que quieres que sea un boton de icono con:
```ts
size="icon"
```

2024-12-16 14:03 UTC, criss8X commented on src/hooks/useTheme.ts
> +}
En este proyecto no hace falta el ReturnType ya que no tenemos que se ponga explicito el tipo de retorno aunque se tiene que hacerse en varios casos en el caso de los hooks no es necesario aqui se puede omitir

2024-12-16 14:07 UTC, criss8X commented on src/hooks/useTheme.ts
> +
espacio de mas

2024-12-23 17:10 UTC, criss8X requested changes
El calendar lo arreglaste perfectamente, ahora hay cosas a tener en cuenta:

ButtonSwitchTheme:
1. Cambiarle el nombre a SwitchTheme unicamente, si el boton switch theme es el unico que cambia de tema, entonces en lugar de crear un hook para el puedes establecer la logica dentro de Switch Theme, va ser mejor.
2. Deberias poner el boton en algun lado, si esta creado debe implementarse en algun sitio. Busca algun sitio sin que rompa con la interfaz en todas las pantallas, para eso deberas usar las herramientas de desarrollo.
3. Debes implementarle una animacion sencilla para darle un toque interesante, hay muchas plataformas que muestran animaciones para cambios de tema puedes usar framermotion.
4.  El uso de literales sin usar la constante:
```ts
theme === "dark" ? <> </> : <></>
```

ahi estas poniendo "dark" es cierto que ese valor no cambiara, pero es una mala practica hacer eso porque normalmente trabajamos con valores que cambian, ya en el hook `useTheme` estableciste una constante, utilizala siempre.

5. Cuando cambia de tema se ve un pequeño bub en el boton de switch theme ya que es ghost y cambia los colores de fondo, eso creo que se puede arreglar con una transision de colores.

Sugerencia:
las constantes DARK_MODE y LIGHT_MODE simplemente se pueden abstraer a un `enum`

```ts
export enum ThemeMode {
Dark = "dark",
Light = "light"
}
```

Te sera mucho mas facil y es mas optimo que constantes sueltas creo.

2025-01-12 17:23 UTC, criss8X approved these changes

2025-01-12 17:23 UTC, merged